TARFILES = Makefile scanner.mll parser.mly ast.mli declcheck.ml

OBJS = parser.cmo scanner.cmo declcheck.cmo

declcheck : $(OBJS)
	ocamlc -o declcheck $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

.PHONY : clean
clean :
	rm -f declcheck parser.ml parser.mli scanner.ml *.cmo *.cmi

# Generated by ocamldep *.ml *.mli
declcheck.cmo: scanner.cmo parser.cmi ast.cmi 
declcheck.cmx: scanner.cmx parser.cmx ast.cmi 
parser.cmo: ast.cmi parser.cmi 
parser.cmx: ast.cmi parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmi 
